version without scenario logic
iduprojects/idu_api pull request #2
Opened 2024-08-12 08:34 UTC by mdvasilyev

2024-08-12 20:05 UTC, kanootoko requested changes
Увидел pull request, забежал на огонек.

**Точно нужна миграция, создающая таблички**.

Желательно вынести функции `UserProjectService` (пример уже есть, и сейчас это сделать проще, чем _когда-нибудь потом_)

Ну и HTTP ошибки бы не кидать из уровня общения с БД, тут еще надо красивое решение придумать.

В идеале ко всему этому бы какие-нибудь тесты уже, но это уже задачка сложного уровня.
isort и black еще позапускайте, пожалуйста (со вторым проблем в этом PR'е нет, а вот импорты бы местами попереставлять)

2024-08-14 18:29 UTC, mdvasilyev commented
Спасибо большое за замечания, основное поправил

2024-08-18 16:49 UTC, kanootoko requested changes
Извиняюсь, пропустил призыв на ревью.
Правки выглядят нормально, но в текущем исполнении не работают (эх, автотесты бы)

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/logic/impl/projects.py
> +            .returning(projects_data.project_id)
Вот тут на создании проекта падает, пропущено `.c`

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/schemas/projects.py
> +class ProjectTerritoryPut(BaseModel):
Вообще, неплохо бы во все операции с проектами пробрасывать пользователя.
В идеале, через хэдер аутентификации с токеном, но раз на создании оно идет в post-запросе, то можно бы пока и в остальные места так же добавить. И перед внесением изменений проверять, что это тот же пользователь

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/schemas/projects.py
> +    parent_id: int | None = Field(description="Project's parent territory id")
Еще одна пользовательская история - нельзя давать возможность использовать как родительскую территорию что-то, что загружено не этом пользователем.

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/handlers/v1/projects.py
> +@projects_router.get(
Ну и сюда пользователя тоже передавать нужно - каждый должен видеть свои проекты.
Плюс, нужно как-то обыграть историю с публичностью. Можно:
- возвращать проекты пользователя + публичные по одному эндпоинту
- возвращать проекты пользователя и чуживе (или вообще все?) публичные в разных эндпоинтах
- возвращать проекты в одном эндпоинте по флажкам, где по умолчанию включены только проекты пользователя, но можно включить и публичные

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/logic/impl/projects.py
> +        await conn.execute(statement_for_territory)
Не тот порядок исполнения, удаление не работает

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/schemas/projects.py
> +    user_id: int | None = Field(None, examples=[1])
Кажется, что пользователь не должен иметь возможность "передать кому-то свой проект", заменив user_id на put/patch'е.

Ну, то есть, передавать поле все еще нужно (так как у нас нет аутентификации - хотя, может, это как раз время ее сделать хоть в каком-то варианте (header `user_id=<int>`, а потом уже на токены заменять), чтобы дальше не мучаться),

2024-08-18 16:49 UTC, kanootoko commented on idu_api/urban_api/logic/impl/projects.py
> +        await conn.execute(statement_for_territory)
К слову, все ли будет нормально, если сначала создастся проект А, потом к его территории создастся проект Б, а потом А удалится?
Честно, не сильно вникал в текущую концепцию. Как по мне, выглядит странно, что проекты создаются к территориям, а не территории к проектам (ну, с учетом того, что у проекта есть ровно одна родительская территория)

2024-08-19 10:51 UTC, Dmitry-Grachev commented on idu_api/urban_api/schemas/projects.py
> +    user_id: int | None = Field(None, examples=[1])
С фронта мы можем передать либо токен пользователя, либо его логин. Токен, кмк, звучит логичнее. С учетом того, что авторизация у нас прикручена, но пока бездействует

2024-08-19 10:57 UTC, Jesusya-26 commented on idu_api/urban_api/schemas/projects.py
> +    parent_id: int | None = Field(description="Project's parent territory id")
Так ведь здесь parent_id — это какая-то реальная территория из territories_data. Как я понял, у нас нет иерархии именно пользовательских территорий (спрашивал об этом у Димы).

2024-08-19 10:59 UTC, Jesusya-26 commented on idu_api/urban_api/logic/impl/projects.py
> +        await conn.execute(statement_for_territory)
Здесь та же история по поводу иерархии пользовательских территорий. 

<s>*возможно я что-то не понимаю</s>

2024-08-20 14:07 UTC, kanootoko commented on idu_api/urban_api/schemas/projects.py
> +    parent_id: int | None = Field(description="Project's parent territory id")
Разобрались

2024-08-20 14:10 UTC, kanootoko commented on idu_api/urban_api/handlers/v1/projects.py
> +@projects_router.get(
Решили два эндпоинта: все созданные пользователем проекты (его приватные и его публичные) и все, которые ему доступны (созданные им приватные + публичные и другие публичные)

2024-08-27 19:40 UTC, kanootoko commented on idu_api/urban_api/handlers/v1/projects.py
> +    """Get all projects."""
Надо бы расширить описание, какие именно проекты будут возвращены, и здесь, и выше

2024-08-27 19:40 UTC, kanootoko commented on idu_api/urban_api/logic/impl/projects.py
> +            return 403
Это уже не HTTPException, но все равно явное завязывание на HTTP-коды ответа.
Это же Python, тут есть исключения, и можно создать свои. Зачем возвращать `ProjectDTO` или `целое число`? Как человек из-вне может догадаться без просмотра кода, что это число на самом деле - код HTTP-ответа, а не, например, идентификатор проекта, если UserProjectService настроен специфическим образом?

Учитывая, что сейчас все эти коды ответа в местах получения все-равно обрабатываются вручную для создания HTTPException'ов, можно точно с тем же успехом было кидать что-нибудь вроде `EntityNotFoundError` и ` AccessDeniedError`.

А в целом можно было бы научить эти классы ошибок самостоятельно выкидывать HTTPException'ы.
Например, я делал так [вот тут](https://github.com/kanootoko/facades-state-evaluation/blob/master/backend/facades_api/utils/exceptions.py), а остальные ошибки наследовал от этой [и переопределял поля](https://github.com/kanootoko/facades-state-evaluation/blob/master/backend/facades_api/logic/exceptions/buildings.py).
Как обычно, это не идеальный кусок кода, и тут тоже не совсем правильно, что ошибки уровня логики (но хотя бы не сами куски логики) знают что-то о маппинге себя в HTTP-коды, но идеи с маппером в миддлваре у меня тогда не было

2024-08-27 19:40 UTC, kanootoko commented on idu_api/urban_api/handlers/v1/projects.py
> +from idu_api.urban_api.utils.dependencies import user_dependency
user_dependency - удобная штука, но тоже придется переделать на миддлварю с конфигурацией, так как нужно будет указывать еще и адрес сервера аутентификации для проверки токена (или отсутствие сервера для того, чтобы не проверять подписи, а верить тому, что приходит просто так, для упрощения тестирования).

Впрочем, если у вас получится сделать красиво, чтобы значение UserDTO пробрасывалось в request в миддлваре, а доставалось через Depends, а не через `request.state.user_dto`  с типизацией каждый раз- я бы на это посмотрел, потому что когда я добавлял сервисы, добиться такого не смог

2024-09-06 19:00 UTC, kanootoko approved these changes
Ну, давайте попробуем

2024-09-06 19:10 UTC, merged